SchoolElectronicJournal/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SchoolElectronicJournal.Interface;
using SchoolElectronicJournal.Models;
using Microsoft.AspNetCore.Identity;

namespace SchoolElectronicJournal.Controllers
{
    public class HomeController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public HomeController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        

        public IActionResult Index()
        {
          
            return View("HomeList");
        }
        [Authorize]
        public async Task<IActionResult> List(string id)
        {

           var use = HttpContext.User.Identity.Name;

            var user = userManager.Users.Single(x => x.UserName == use);
            if (string.IsNullOrEmpty(id))
            {
                id = user.Id;
            }
            var role = await userManager.GetRolesAsync(user);
             ViewBag.UserId = id;
             return View(role);           
            
        }
    }
}

SchoolElectronicJournal/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SchoolElectronicJournal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolElectronicJournal.Controllers
{
    [Authorize(Roles ="admin")]
    public class RolesController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public RolesController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }
        
        public IActionResult Index()
        {
            return View(userManager.Users.ToList());
        }

       

        
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        
        public ActionResult Edit(int id)
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

       
        public ActionResult Delete(int id)
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SchoolElectronicJournal/Views/Home/HomeList.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <title>Электронный журнал</title>
    <link href="~/css/StyleHome.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <h1 class="first">Добро пожаловать на наш сайт</h1>
    <div class="two">
        <ul>
            <li><a class="three" href="FirstList.html">Главная</a></li>
            <li>Контакты</li>
            <li>О нас</li>
            
            <li><a class="three" asp-controller="Account" asp-action="Registr">Регистрация</a></li>
            <li><a class="three" asp-controller="Home" asp-action="List">Профиль</a></li>
            <li><a class="three" asp-controller="Account" asp-action="Login">Войти</a></li>
        </ul>
    </div>
</body>
</html>

SchoolElectronicJournal/Views/Home/List.cshtml
@model IEnumerable<string>
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Профиль</title>
    <link href="~/css/styleProf.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div class="one">
        <ul class="four">
            <li class="li"><a class="three" href="FirstList.html">Главная</a></li>
            <li class="li">Контакты</li>
            <li class="li">О нас</li>
            <li class="li"><a class="three" href="registraation.html">Регистрация</a></li>
            
            @if (Model.Contains("admin"))
            {
            <li class="li"><a class="three" asp-controller="Roles" asp-action="Index">Администрация</a></li>
            }
            <li class="li"><a class="three" asp-controller="User" asp-action="Index" asp-route-userid="@ViewBag.UserId">Данные</a></li>
            <li class="li"><a class="three" asp-controller="Account" asp-action="Logout">Выйти</a></li>
        </ul>
    </div>
    <h1>Ваш профиль</h1>
    <div class="cl">
        <h3>Классы</h3>
    </div>
    <div class="sum">
        <ol>
            <li><a href="~/Class/Index?id=@ViewBag.UserId" class="slka">Список классов</a></li>
        </ol>

    </div>
    <h3>Предмет</h3>
    <div class="list">
        <ol>
            <li>
                <a href="~/Lesson/Index?id=@ViewBag.UserId"
                   class="slka">
                    Список предметов
                </a>
            </li>
        </ol>
    </div>
</body>
</html>